### ISSUE TITLE
MC 1.12 support

### ISSUE THREAD

**Issue by confuser** [BanManagement/ReportsLogger#3]
Currently throws following error:
```
[12:35:43 ERROR]: Error occurred while enabling ReportsLogger v1.0.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: org.apache.logging.log4j.core.layout.PatternLayout.createLayout(Ljava/lang/String;Lorg/apache/logging/log4j/core/config/Configuration;Lorg/apache/logging/log4j/core/pattern/RegexReplacement;Ljava/lang/String;Ljava/lang/String;)Lorg/apache/logging/log4j/core/layout/PatternLayout;
        at me.confuser.banmanager.reportslogger.listeners.LogServerAppender.<init>(LogServerAppender.java:21) ~[?:?]
        at me.confuser.banmanager.reportslogger.ReportsLogger.setupListeners(ReportsLogger.java:90) ~[?:?]
        at me.confuser.banmanager.reportslogger.ReportsLogger.onEnable(ReportsLogger.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-ac83d69-701b064]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-ac83d69-701b064]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-ac83d69-701b064]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-ac83d69-701b064]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-ac83d69-701b064]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-ac83d69-701b064]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-ac83d69-701b064]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-ac83d69-701b064]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-ac83d69-701b064]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-ac83d69-701b064]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by mr2013** [comment]
Not heavily tested, will likely break backward compatibility

    diff --git a/pom.xml b/pom.xml
    index ea7edc0..e4344cf 100644
    --- a/pom.xml
    +++ b/pom.xml
    @@ -35,7 +35,7 @@
         <repositories>
             <repository>
                 <id>bukkit-repo</id>
    -            <url>http://repo.bukkit.org/content/groups/public</url>
    +            <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
             </repository>
             <repository>
                 <id>confuser-repo</id>
    @@ -50,13 +50,13 @@
             <dependency>
                 <groupId>org.bukkit</groupId>
                 <artifactId>bukkit</artifactId>
    -            <version>1.8.8-R0.1-SNAPSHOT</version>
    +            <version>1.12-R0.1-SNAPSHOT</version>
                 <scope>provided</scope>
             </dependency>
             <dependency>
                 <groupId>org.bukkit</groupId>
                 <artifactId>craftbukkit</artifactId>
    -            <version>1.8.8-R0.1-SNAPSHOT</version>
    +            <version>1.12-R0.1-SNAPSHOT</version>
                 <scope>provided</scope>
             </dependency>
             <dependency>
    @@ -75,4 +75,4 @@
         <properties>
             <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         </properties>
    -</project>
    \ No newline at end of file
    +</project>
    diff --git a/src/main/java/me/confuser/banmanager/reportslogger/listeners/LogServerAppender.java b/src/main/java/me/confuser/banmanager/reportslogger/listeners/LogServerAppender.java
    index f3aa364..86c6926 100644
    --- a/src/main/java/me/confuser/banmanager/reportslogger/listeners/LogServerAppender.java
    +++ b/src/main/java/me/confuser/banmanager/reportslogger/listeners/LogServerAppender.java
    @@ -18,9 +18,7 @@ public class LogServerAppender extends AbstractAppender {
     
       public LogServerAppender(ReportsLogger plugin) {
         super("Log4JAppender", null,
    -            PatternLayout.createLayout(
    -                    "[%d{HH:mm:ss} %level]: %msg",
    -                    null, null, null, null), false);
    +            PatternLayout.newBuilder().withPattern("[%d{HH:mm:ss} %level]: %msg").build(), false);
     
         this.plugin = plugin;
         queue = EvictingQueue.create(plugin.getConfiguration().getAmount());
    @@ -57,7 +55,7 @@ public class LogServerAppender extends AbstractAppender {
     
         if (!ignore) {
           // Not thread safe, sync this if causes issues
    -      queue.add(new LogData(message, log.getMillis() / 1000L));
    +      queue.add(new LogData(message, log.getTimeMillis() / 1000L));
         }
       }
     }

**Comment by confuser** [comment]
Thanks @mr2013, I'll take a look.
